feat: add solution for 06-koajs 01-chat-app
js-tasks-ru/nodejs-20210126_mary-gushchina pull request #6
Opened 2021-02-14 17:26 UTC by glowlh

2021-02-14 17:28 UTC, glowlh commented on 06-koajs/01-chat-app/app.js
>  router.get('/subscribe', async (ctx, next) => {
У меня не получилось отправлять адекватным способом сообщения обоим юзерам с использованием setTimeout/setInterval. Было бы неплохо узнать и решение с ними

2021-02-15 11:24 UTC, tadjik1 commented on 06-koajs/01-chat-app/app.js
>  router.get('/subscribe', async (ctx, next) => {
хм, честно говоря адекватных и нет с таймерами :)
ну наверное как идея что-то вроде:

```
let msg;
let timer;

function loop() {
  if (!msg) {
    timer = setTimeout(loop, 5000);
    return;
  }

  // send response
}

loop();
```

ну и соответственно в какой-то момент выставлять значение `msg`. но адекватным такое решение не назвать, пожалуй)

2021-02-15 11:25 UTC, tadjik1 commented on 06-koajs/01-chat-app/app.js
> +  users.forEach((resolve) => resolve(message));
нужно еще очищать массив, иначе будут накапливаться пользователи

2021-02-15 11:25 UTC, glowlh commented on 06-koajs/01-chat-app/app.js
>  router.get('/subscribe', async (ctx, next) => {
Спасибо) Просто, думала, что "каноничным" было решение на которые намекали на занятии с таймером

2021-02-15 11:26 UTC, tadjik1 requested changes
@glowlh отличное решение, идея схвачена абсолютно верно. небольшой нюанс только с очисткой массива нужно поправить

2021-02-15 11:26 UTC, glowlh commented on 06-koajs/01-chat-app/app.js
>  router.get('/subscribe', async (ctx, next) => {
Но с таймером все равно получается, что нужно следить за количеством активных юзеров

2021-02-15 11:27 UTC, glowlh commented on 06-koajs/01-chat-app/app.js
> +  users.forEach((resolve) => resolve(message));
да, главное и забыла

2021-02-15 18:56 UTC, tadjik1 commented on 06-koajs/01-chat-app/app.js
>  router.get('/subscribe', async (ctx, next) => {
ой, прошу прощения если намекал, никаких таймеров тут не нужно, ваше решение абсолютно верное, моё практически такое же :)

2021-02-15 18:56 UTC, tadjik1 approved these changes
👍

2021-02-15 18:57 UTC, merged

2021-02-15 18:57 UTC, jsru commented
К сожалению, PR не может быть замержен, tadjik1 вероятно сможет помочь.